### ISSUE TITLE
fork/exec /usr/bin/sdiag: no such file or directory

### ISSUE THREAD

**Issue by jeevadotnet** [vpenso/prometheus-slurm-exporter#15]
Good day

`Ubuntu 16.04 LTS`

I've compiled and ran the prometheus slurm exporter as per the guide on a VM that is connected to the slurm cluster, so it is able to get information from `sinfo`, `squeue`, etc. 

As per the guide for debian it says install `jessie-backports`, that part doesn't work. (unable to locate such package)

My issue is, after I've compiled and run the bin file. Once I open the url (wget or curl) localhost:8080/metrics it gives a ERROR 404 page. 

```root@slex-test:/opt/prometheus-slurm-exporter# wget http://localhost:8080/metrics
--2019-06-10 11:44:02--  http://localhost:8080/metrics
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
```

Eventually the process stops with this:
```root@slex-test:/opt/prometheus-slurm-exporter/bin# ./prometheus-slurm-exporter
INFO[0000] Starting Server: :8080                        source="main.go:43"

2019/06/10 11:36:00 fork/exec /usr/bin/sdiag: no such file or directory

```
And therefore I cannot connect at all then.

Any steps to troubleshoot this? Is there also a way to change the ports?

**Comment by mtds** [comment]
Hi.

I will break down my answer in three points:

1. Compile the source and jessie-backports.

The README refers explicitly to **Debian Jessie**, which was the first platform where this exporter was developed. Debian and Ubuntu are not always 100% compatible, as you have seen.
The jessie-backports were discontinued by the Debian FTP maintainers ([announce here](https://lists.debian.org/debian-backports-announce/2018/07/msg00000.html)).

2. /usr/bin/sdiag

Where did you install your Slurm command line utilities? As you have seen, once the exporter is called over HTTP (e.g. with curl) it tries to launch various commands (sdiag, squeue, etc.) but those binaries have to be installed under the ``/usr/bin`` path otherwise the exporter will fail. The only solution is to edit the source files involved (squeue.go, scheduler.go) and remove the full path from the ``cmd := exec.Command(...)`` lines). This is actually a limitation, I guess I will update the sources to remove hard coded paths.

3. Listening port

The port 8080 is not fixed, it can be changed with a command line option:
```bash
:~$ prometheus-slurm-exporter -h
Usage of ./prometheus-slurm-exporter:
  -listen-address string
    	The address to listen on for HTTP requests. (default ":8080")
  -log.format value
    	Set the log target and format. Example: "logger:syslog?appname=bob&local=7" or "logger:stdout?json=true" (default "logger:stderr")
  -log.level value
    	Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal] (default "info")
```

**Comment by jeevadotnet** [comment]
Good day mtds

Thanks for your input so far, much appreciated. 

I got the slurm exporter working by using your steps in relation with the hard coded paths. prometheus & grafana also nicely linked up.

Regards

**Comment by mtds** [comment]
Nice. If everything is working on your side,  I will close this issue.

I took the chance also to update the info in the README.

Regards,
   Matteo

**Comment by jeevadotnet** [comment]
Hi @mtds 

Hope you can maybe help me.

I created a service for the slurm exporter but need a second pair of eyes to see why it fails.

So below you can see the status of the service and it presents the issue of "sinfo" not found.

```Jul 01 10:59:37 slurm-login prometheus-slurm-exporter[24230]: 2019/07/01 10:59:37 exec: "sinfo": executable file not found in $PATH```



```
ubuntu@slurm-login:~$ sudo systemctl status slurm-exporter.service
slurm-exporter.service - Prometheus Slurm Exporter.
   Loaded: loaded (/lib/systemd/system/slurm-exporter.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-07-01 10:59:37 SAST; 5min ago
  Process: 24230 ExecStart=/usr/bin/prometheus-slurm-exporter -listen-address :9118 (code=exited, status=1/FAILURE)
 Main PID: 24230 (code=exited, status=1/FAILURE)

Jul 01 10:59:19 slurm-login systemd[1]: Started Prometheus Slurm Exporter..
Jul 01 10:59:19 slurm-login prometheus-slurm-exporter[24230]: time="2019-07-01T10:59:19+02:00" level=info msg="Starting Server: :9118" source="main.go:43"
Jul 01 10:59:37 slurm-login prometheus-slurm-exporter[24230]: 2019/07/01 10:59:37 exec: "sinfo": executable file not found in $PATH
Jul 01 10:59:37 slurm-login systemd[1]: slurm-exporter.service: Main process exited, code=exited, status=1/FAILURE
Jul 01 10:59:37 slurm-login systemd[1]: slurm-exporter.service: Failed with result 'exit-code'.
```

But if I run `sinfo` it works correctly.

```ubuntu@slurm-login:~$ sinfo
PARTITION         AVAIL  TIMELIMIT  NODES  STATE NODELIST
Main*                up 3-00:00:00      9    mix slwrk-[101,131-138]
Main*                up 3-00:00:00     21   idle slwrk-[102-120,139-140]
cbio                 up 21-00:00:0      1    mix slwrk-121
cbio                 up 21-00:00:0      9   idle slwrk-[122-130]
JupyerSpawnerONLY    up   infinite      2    mix slwrk-[206,208]
JupyerSpawnerONLY    up   infinite      2  alloc slwrk-[203,207]
JupyerSpawnerONLY    up   infinite      4   idle slwrk-[201-202,204-205]
ubuntu@slurm-login:~$
```

` scheduler.go`
```// Execute the sdiag command and return its output
func SchedulerData() []byte {
  cmd := exec.Command("/opt/slurm/bin/sdiag")
```

`queue.go`
```// Execute the squeue command and return its output
func QueueData() []byte {
        cmd := exec.Command("/opt/slurm/bin/squeue", "-r", "-h", "-o %A,%T,%r", "--states=all")
        stdout, err := cmd.StdoutPipe()
```

`service file`
```
[Unit]
Description=Prometheus Slurm Exporter.

[Service]
Type=simple
ExecStart=/usr/bin/prometheus-slurm-exporter -listen-address :9118

[Install]
WantedBy=multi-user.target
```

**Comment by mtds** [comment]
The only thing I can think about is that, since you are executing the
exporter via 'sudo', the user which is running the
exporter does not have the '/opt/slurm/bin' in its $PATH.

Also, the 'sinfo' command is executed by nodes.go. If you did not
modify it to execute a Slurm command from '/opt/slurm/bin'
(as you did for scheduler.go and queue.go) then I guess you'll always
get the 'executable file not found in $PATH' error message.

Best regards,
Matteo

On Mon, Jul 1, 2019 at 11:13 AM jeevadotnet <notifications@github.com> wrote:
>
> Hi @mtds
>
> Hope you can maybe help me.
>
> I created a service for the slurm exporter but need a second pair of eyes to see why it fails.
>
> So below you can see the status of the service and it presents the issue of "sinfo" not found.
>
> Jul 01 10:59:37 slurm-login prometheus-slurm-exporter[24230]: 2019/07/01 10:59:37 exec: "sinfo": executable file not found in $PATH
>
> ubuntu@slurm-login:~$ sudo systemctl status slurm-exporter.service
> slurm-exporter.service - Prometheus Slurm Exporter.
>    Loaded: loaded (/lib/systemd/system/slurm-exporter.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Mon 2019-07-01 10:59:37 SAST; 5min ago
>   Process: 24230 ExecStart=/usr/bin/prometheus-slurm-exporter -listen-address :9118 (code=exited, status=1/FAILURE)
>  Main PID: 24230 (code=exited, status=1/FAILURE)
>
> Jul 01 10:59:19 slurm-login systemd[1]: Started Prometheus Slurm Exporter..
> Jul 01 10:59:19 slurm-login prometheus-slurm-exporter[24230]: time="2019-07-01T10:59:19+02:00" level=info msg="Starting Server: :9118" source="main.go:43"
> Jul 01 10:59:37 slurm-login prometheus-slurm-exporter[24230]: 2019/07/01 10:59:37 exec: "sinfo": executable file not found in $PATH
> Jul 01 10:59:37 slurm-login systemd[1]: slurm-exporter.service: Main process exited, code=exited, status=1/FAILURE
> Jul 01 10:59:37 slurm-login systemd[1]: slurm-exporter.service: Failed with result 'exit-code'.
>
> But if I run sinfo it works correctly.
>
> PARTITION         AVAIL  TIMELIMIT  NODES  STATE NODELIST
> Main*                up 3-00:00:00      9    mix slwrk-[101,131-138]
> Main*                up 3-00:00:00     21   idle slwrk-[102-120,139-140]
> cbio                 up 21-00:00:0      1    mix slwrk-121
> cbio                 up 21-00:00:0      9   idle slwrk-[122-130]
> JupyerSpawnerONLY    up   infinite      2    mix slwrk-[206,208]
> JupyerSpawnerONLY    up   infinite      2  alloc slwrk-[203,207]
> JupyerSpawnerONLY    up   infinite      4   idle slwrk-[201-202,204-205]
> ubuntu@slurm-login:~$
>
> scheduler.go
>
> func SchedulerData() []byte {
>   cmd := exec.Command("/opt/slurm/bin/sdiag")
>
> queue.go
>
> func QueueData() []byte {
>         cmd := exec.Command("/opt/slurm/bin/squeue", "-r", "-h", "-o %A,%T,%r", "--states=all")
>         stdout, err := cmd.StdoutPipe()
>
> service file
>
> [Unit]
> Description=Prometheus Slurm Exporter.
>
> [Service]
> Type=simple
> ExecStart=/usr/bin/prometheus-slurm-exporter -listen-address :9118
>
> [Install]
> WantedBy=multi-user.target
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Those parts of the system that you can hit with a hammer are called hardware;
those program instructions that you can only curse at are called software.

**Comment by jeevadotnet** [comment]
Hi I came right thanks, I had to set the environmental path in the service.

Just having an issue now where it crashes after 12 hours or so which i still have to figure out.

``` slurm-exporter.service - Prometheus Slurm Exporter.
   Loaded: loaded (/lib/systemd/system/slurm-exporter.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-07-02 13:50:07 SAST; 2 days ago
  Process: 22704 ExecStart=/usr/bin/prometheus-slurm-exporter -listen-address :9118 (code=exited, status=2)
 Main PID: 22704 (code=exited, status=2)

Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]: main.SchedulerGetMetrics(0x457684)
Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]:         /tmp/prometheus-slurm-exporter-master/scheduler.go:83 +0x27
Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]: main.(*SchedulerCollector).Collect(0xc4201862c0, 0xc420e90960)
Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]:         /tmp/prometheus-slurm-exporter-master/scheduler.go:119 +0x34
Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc42018e0d0, 0xc420e90960, 0x89b280, 0xc4201862c0)
Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]:         /usr/share/gocode/src/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
Jul 02 13:50:07 slurm-login prometheus-slurm-exporter[22704]:         /usr/share/gocode/src/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x302
Jul 02 13:50:07 slurm-login systemd[1]: slurm-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 02 13:50:07 slurm-login systemd[1]: slurm-exporter.service: Failed with result 'exit-code'.
```

**Comment by mtds** [comment]
You have most likely stumbled upon the issue #18. You can check the discussion thread but a possible solution is available (for the moment) in the **regexp_parse** branch in this repository.

As soon as the tests from the other users are finished, I will merge this branch into master.
