### ISSUE TITLE
User and Account info?

### ISSUE THREAD

**Issue by smithnp** [vpenso/prometheus-slurm-exporter#25]
How difficult would it be to get user and account info into the exporter?  Use cases would be things like pie charts of jobs per account and/or user for the cluster.

**Comment by mtds** [comment]
I would rather suggest you'll extract this info from Slurm directly via the command line and then plot the results. We are doing similar things with a mix of Python and Ruby scripts.

The point is also to not overload the Prometheus instance with a lot of a data which is volatile anyway: users and their respective accounts may come and go quite often.

**Comment by smithnp** [comment]
Yes, I am not too familiar with go, but I did look around at the code and decided that a seemingly simple feature add could be opening a huge can of worms as far as how much info the exporter is processing.  Slurm can be configured in so many ways that it would not be feasible to export such data in a way that it could be useful to all types of configurations.  Thanks for the response!

Nick


________________________________

**Comment by mtds** [comment]
Just a little tip, although maybe you already know about these [SlurmTools](https://github.com/OleHolmNielsen/Slurm_tools).

They are a set of wrapper scripts on top of Slurm commands, developed by [Ole Holm Nielsen]( https://github.com/OleHolmNielsen) from the Technical University of Denmark.

Some of these scripts maybe could be useful to you (also as an inspiration to develop something
else on top of it).

**Comment by smithnp** [comment]
Yep, thanks.  My organization just recently switched to Slurm on all of our clusters.  The docs and wrappers at TUD have been very helpful to my team in making the transition fairly smooth for our users.  After more thought, the metrics I am looking for may be better served to be collected and displayed in something more like an ELK stack anyway.  I do have this exporter for slurm running in a test environment, and the engineering team likes it as a quick "how's the cluster doing", we REALLY enjoy that we can run it in a self contained manner rather than having to install the exporter on the slurmctld or slurmdbd systems

________________________________

**Comment by mtds** [comment]
> I do have this exporter for slurm running in a test environment, and the engineering team likes it 
> as a quick "how's the cluster doing", we REALLY enjoy that we can run it in a self contained 
> manner rather than having to install the exporter on the slurmctld or slurmdbd systems.

Nice to know that you found this exporter useful and nimble enough for your deployment. We are always interested in feedback anyway and we try to merge pull requests as well (whenever feasible,
although I am behind schedule in this regard at the moment...).

I will close this issue then.

**Comment by timkahlke** [comment]
Sorry for re-opening this but I was under the impression that the exporter already does something kind of similar:

> The following information about jobs are also extracted via squeue:
> 
> Running/Pending/Suspended jobs per SLURM Account.
> Running/Pending/Suspended jobs per SLURM User.

However, I can't find the metrics in the exporter output.
