### ISSUE TITLE
Doesn't build on EL7

### ISSUE THREAD

**Issue by LaHaine** [vpenso/prometheus-slurm-exporter#26]
I've tried the CentOS build instructions on Scientific Linux 7.8 and failed:
```
$ make test
$GOPATH/go.mod exists but should not
make: *** [test] Fehler 1
```
This is with golang 1.13.6 from the EPEL repository.

**Comment by mtds** [comment]
I have updated the README with my latest commit, take a look and try to repeat the procedure from scratch.
It should work now. I did not check before but latest version of Golang are quite picky in setting up the GOPATH.

**Comment by LaHaine** [comment]
With the instructions from commit 482c00e I could build on EL 7.7.
