### ISSUE TITLE
Nodes not shown when in drain state.

### ISSUE THREAD

**Issue by maxl-hnj** [vpenso/prometheus-slurm-exporter#3]
Not sure if it's me who is doing something wrong or if it's somewhere in the code but when i put a node in drain-state it does not show up at all, it just disappears from the node count all together.

Please let me know what i need to do to troubleshoot this.

**Comment by mtds** [comment]
Hi.

You are absolutely right: the counter for the nodes in 'drain' state was not properly incremented.
It was a problem on our exporter itself but I have fixed the bug with the commit 80a67f4 (tag 0.2). 

I am already testing it on our Slurm controller and it looks like it is working fine. Can you make a test
and let me know if it works on your side too?

**Comment by maxl-hnj** [comment]
Yes, works like a charm now. 

Thanks!
