### ISSUE TITLE
Error while building prometheus-slurm-exporter

### ISSUE THREAD

**Issue by deepikaPav** [vpenso/prometheus-slurm-exporter#36]
Hi,
I get the following error when I try to build ,
# command-line-arguments
./main.go:34:26: undefined: NewPartitionsCollector

Can you please let me know how to resolve this issue?

**Comment by mtds** [comment]
There is a typo in the _DEVELOPMENT_ document, I have just corrected it. The build command it is as follows:
```bash
go build -o bin/prometheus-slurm-exporter {main,accounts,cpus,nodes,partitions,queue,scheduler,users}.go
```

Otherwise, if you use ``make``, you should not have troubles building the binary.
