### ISSUE TITLE
no metrics

### ISSUE THREAD

**Issue by hoba87** [vpenso/prometheus-slurm-exporter#42]
I've followed the DEVELOPMENT.md for installation, but when trying to use the command `curl http://localhost:9103/metrics` after `./bin/prometheus-slurm-exporter --listen-address="0.0.0.0:9103"`, there is no output and the curl command waits until I kill the exporter.
The output from the exporter is only:
`INFO[0000] Starting Server: 0.0.0.0:9103                        source="main.go:48"`

Any idea why? I use CentOS 8.2 with Prometheus 2.22.0 and Slurm 20.02.5.

**Comment by mtds** [comment]
I need a little bit more information: 

1) Are you launching the _curl_ command on the same host or VM where the exporter is running?
2) Is the exporter running where _sinfo_, _squeue_ etc. are properly installed and able to query your Slurm instance?
3) Do you have firewall policies (e.g. implemented via _firewalld_ ) which limit/restrict network connections?

**Comment by hoba87** [comment]
> Are you launching the curl command on the same host or VM where the exporter is running?

yes, on the same host

> Is the exporter running where sinfo, squeue etc. are properly installed and able to query your Slurm instance?

yes, the path of slurms bin directory is added to the PATH variable

> Do you have firewall policies (e.g. implemented via firewalld ) which limit/restrict network connections?

firewalld is installed but only used for external network, however I have tried it with temporarily disabling the firewall, with the same result.

**Comment by hoba87** [comment]
I think the problem was using Slurm with Accouting to text file, because an sacct run takes very long. I have switched to slurmdbd now, with no problem anymore.
