### ISSUE TITLE
Default port should be 9341

### ISSUE THREAD

**Issue by lahwaacz** [vpenso/prometheus-slurm-exporter#44]
Why is the default port 8080 when there is an [allocated port 9341](https://github.com/prometheus/prometheus/wiki/Default-port-allocations)?

**Comment by mtds** [comment]
We are aware of the official list but port 8080 was used initially in our test in the internal network,
so we never changed.

I do not believe it is an issue, considering that there is the option to change the port: ``listen-address``

**Comment by lahwaacz** [comment]
I'm aware of `listen-address` but I don't understand why you insist on keeping the status quo. According to [IANA](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers), 8080 is an "alternative port for HTTP" which is frequently used by web servers (or components behind reverse proxies) so there is a high risk of conflicts. Using it as the default port might have been fine initially but I don't see why it should be kept forever, especially considering there is a port number allocated (at least by Prometheus).

**Comment by sjpb** [comment]
Thanks for the exporter. Just trying to deploy for the 1st time and I've run into the same issue. Thought using `8080` as described [here](https://github.com/vpenso/prometheus-slurm-exporter/blob/master/DEVELOPMENT.md) was a bit odd, went to see what alternative I could use instead and noticed that `9341` is already [allocated](https://github.com/prometheus/prometheus/wiki/Default-port-allocations).
