### ISSUE TITLE
Slurm 20 compatible?

### ISSUE THREAD

**Issue by jeevadotnet** [vpenso/prometheus-slurm-exporter#59]
Good day

I previously used this exporter on ubuntu 16 and an older version of slurm. It worked correctly.

However I'm running Ubuntu 18 LTS with Slurm 20 and get a "404" error when I run the exporter.

```
Jul 22 10:43:05 slurm-login systemd[1]: Started slurm exporter for prometheus.
Jul 22 10:43:05 slurm-login prometheus-slurm-exporter[4706]: time="2021-07-22T10:43:05+02:00" level=info msg="Starting Server: :9341" source="main.go:59"
Jul 22 10:43:05 slurm-login prometheus-slurm-exporter[4706]: time="2021-07-22T10:43:05+02:00" level=info msg="GPUs Accounting: true" source="main.go:60"
root@slurm-login:/opt/prometheus-slurm-exporter-0.19# curl localhost:9341
404 page not found
```
I'm able to run items such as `squeue`, `sinfo` etc from anywhere on the box and it works correctly.

Any ideas?

**Comment by mtds** [comment]
Perhaps this is not clear enough from the documentation but the main entry point of the exported data is the following (I assume you have set the TCP port with the ``-listen-address`` option):
```
http://localhost:9341/metrics
```
Otherwise, as you have seen, the ``404 page not found`` error message is produced.

A note about Slurm compatibility: this exporter was developed and tested with Slurm version **18.08.8**. At the moment we do not have the chance to make tests on newer versions, so you may encounter some bug here and there due to the difference in the output parsed from the command line utilities (e.g. ``sinfo``, ``squeue``, etc.).

**Comment by jeevadotnet** [comment]
Hi, thanks for the reply

It is running as the following with GPU enabled since we have a bunch of Tesla A100/ P100's and the port assigned to the one provided by prometheus exporter listen ports:

```
4706 /usr/sbin/prometheus-slurm-exporter -gpus-acct -listen-address :9341
```

```
netstat -plnt | grep '9341'
tcp6       0      0 :::9341                 :::*                    LISTEN      25354/prometheus-sl
```

```
curl http://localhost:9341/metrics
curl: (52) Empty reply from server
```

However like I said, we're running SLURM 20, so that might be an issue.

**Comment by iamtroy412** [comment]
We are running this exporter in our environment using Slurm version **20.02.5** without issue. My suggestion is to check and make sure that the account that the exporter is running as has the correct `$PATH` set to be able to see all of the Slurm commands (e.g. `sinfo`, `squeue`, etc.).

**Comment by jeevadotnet** [comment]
I was able to run `squeue`, `sinfo` from anywhere on the server under `ubuntu` and `root` but to get it working I added the `Environment` PATH under my service:

```
[Unit]
Description=slurm exporter for prometheus
After=syslog.target
After=network.target

[Service]
ExecStart=/usr/sbin/prometheus-slurm-exporter -gpus-acct -listen-address :9341
Environment=PATH=/opt/slurms/slurm-20-02-3-1/bin:/usr/sbin
Type=simple
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
```

I now get metrics when `curl localhost:9341/metrics` 
Thank you
