### ISSUE TITLE
Job Status not retrieved 

### ISSUE THREAD

**Issue by carlos-encs** [vpenso/prometheus-slurm-exporter#92]
Hi

slurm-exporter can't scrape job status from Slurm 22.05.5

slurm_queue_cancelled 0
slurm_queue_completed 0
slurm_queue_completing 0
slurm_queue_configuring 0
slurm_queue_failed 0
slurm_queue_node_fail 0
slurm_queue_pending 0
slurm_queue_pending_dependency 0
slurm_queue_preempted 0
slurm_queue_running 0
slurm_queue_suspended 0

Any ideas?

**Comment by mtds** [comment]
@carlos-encs Have you tried using the version in the [development branch](https://github.com/vpenso/prometheus-slurm-exporter/tree/development)?

**Comment by mtds** [comment]
No feedback, so I will close it.
